### ISSUE TITLE
Add tests for Cabal idris

### ISSUE THREAD

**Issue by david-christiansen** [idris-hackers/idris-mode#227]
It should test against the latest release as well as the Git Idris, using `allow_failures` in Travis.

**Comment by abailly** [comment]
Is this still relevant? Looks like Idris is now using `stack`

**Comment by david-christiansen** [comment]
What was meant by this is that the latest Hackage release and the current Git version should both be tested.

**Comment by jsoo1** [comment]
Since I've been fixing up travis, I think I'm going to pick this up. Do you think the idris version should be part of the matrix or just as a separate step?

**Comment by david-christiansen** [comment]
I think it makes sense as part of the matrix. Thanks!

**Comment by jsoo1** [comment]
Alright, thank you. I'll give it a go.
