### ISSUE TITLE
add "--package" "effects" to idris-mode.el

### ISSUE THREAD

**Issue by joe9** [idris-hackers/idris-mode#271]
Hello,

error when using emacs with idris-mode on *.idr files using effects:

```
starting flycheck-buffer
Checker idris returned non-zero exit code 1, but no errors from output: Can't find import Effect/StdIO

Checker definition probably flawed.
```

Changing line 135 of idris-mode.el to the below fixed the above error:

```
       :command ("idris" "--check" "--nocolor" "--warnpartial" "--package" "effects" source)
```

Thanks

**Comment by bigos** [comment]
So, five years later, what is the solution to the problem? Is it documented elsewhere?

**Comment by jsoo1** [comment]
Yes it is. The way it's done now is with `idris-load-file` or adding a dependency to an `ipkg` file.

 - https://github.com/idris-hackers/idris-mode#package-files
 - https://github.com/idris-hackers/idris-mode#using-packages
