### ISSUE TITLE
Can't get any of the keys to work

### ISSUE THREAD

**Issue by pharpend** [idris-hackers/idris-mode#286]
Hi, I'm on GNU Emacs 24.4.1 on Gentoo.

I got idris-mode installed through MELPA (or one of the ELPAs, I'm not sure which). It successfully initializes when I open a `.idr` file. None of your instructions work thereafter. Specifically, none of the keybindings work.

`C-c C-l` is undefined. Ditto for  `C-c C-d`,  `C-c C-n`, `C-c C-p` `C-u C-u C-c C-l`, and so on.

Your README says to pin idris-mode to melpa stable, and to learn about this by looking at the documentation for `package-pinned-packages`. However, `C-h d package-pinned-packages` returns no results.

**Comment by david-christiansen** [comment]
Based on further discussion on IRC, it seems that the problem is that the hooks that define the keybindings aren't being run.

**Comment by pharpend** [comment]
Yes, this is fixed now. It was my stupidity causing the issue. Thank you for the help, @david-christiansen !

**Comment by david-christiansen** [comment]
I would hardly call this stupidity - most modes don't do keybindings in hooks the way that idris-mode does, so it was a reasonable confusion.
