### ISSUE TITLE
Aquamacs (OS X) Warnings and Errors

### ISSUE THREAD

**Issue by dmzimmerman** [idris-hackers/idris-mode#292]
When entering idris-mode (installed from MELPA) on the current version of Aquamacs (3.2a, based on Emacs 24.4.51.2), the following warnings and errors occur:

```
Warning: Key <delete> already bound to `delete-char' by minor modes (osx-key-mode).  Use `define-key' instead.
Invalid face reference: quote [108 times]
```
It appears that idris-mode basically works regardless, but my inexperience with it makes me unable to tell whether it is doing everything it should.

**Comment by david-christiansen** [comment]
@dmzimmerman this is fixed now, right?

**Comment by dmzimmerman** [comment]
Yes, it is fixed.
