### ISSUE TITLE
Stop adding key bindings with hooks

### ISSUE THREAD

**Issue by david-christiansen** [idris-hackers/idris-mode#293]
It seems that the choice to add all keybindings with hooks has had some unexpected negative consequences. The first is that an error on the mode hook will render it completely unusable, which is attested to in the README now. It's much better to eliminate the possibility of errors than it is to tell how to fix them.

The other is that `local-set-key` doesn't fail the way we necessarily would expect - see #292 for an example. While that is with Aquamacs, I imagine that other minor modes could cause the same problem.

On the other hand, we have gotten two real benefits from the keybindings as hooks system: consistency and configurability.  The first is perhaps most important: the hooks system has ensured that we don't forget to bind a new command in all of the submodes for which it is valid. The second is that it's easy to do a kind of "total-conversion mod" of idris-mode's keybindings.

We can get back the consistency by replacing the hooks with functions that take a keymap as an argument and define the appropriate keys, calling these manually in the mode initialization. This is equivalently convenient.

I haven't heard of anyone making their own complete keymap, so I don't think it's an important use case.. If someone wants to,, they can probably just `(setq idris-mode-map (make-sparse-keymap))`.

Any objections?

**Comment by hannesm** [comment]
I personally didn't understand the hook-way in the first place - and am happy to revert back to functions and keymaps (as I'm used to in emacs modes ;)
