### ISSUE TITLE
:module, command not recognized or supported

### ISSUE THREAD

**Issue by jasonhemann** [idris-hackers/idris-mode#295]
In the idris-repl within emacs, the :module command isn't working for me since I upgraded to the most recent idris-mode package.

Welcome to Idris REPL!
λΠ> :module 
Usage is :module <module>
λΠ> :module Data.Vect
command not recognized or not supported
λΠ> 

Outside of emacs, simply at a terminal, this works without error. 

Idris> :module 
Usage is :module <module>
Idris> :module Data.Vect
*Vect> 

Can your replicate this behavior, or does :module work for you within emacs as well?

**Comment by mindbound** [comment]
I can replicate this (GNU Emacs 24.4.1, MELPA idris-mode 20150118.1409).

**Comment by david-christiansen** [comment]
This is actually the intended behavior (which may be wrong! let me know!)

The model that idris-mode goes for is to have a REPL that is serving a particular source buffer. The way to bring things into scope into the REPL is thus to bring them into scope in the source buffer and `C-c C-l` it. This way, you don't end up with radically divergent state between the two.

On the other hand, we already support things like `:let`. Perhaps support should be added for `:module`.

**Comment by soimort** [comment]
I think it would be useful to have `:module` in idris-mode (so one can play around with a standard module without leaving emacs or starting another REPL in terminal). However, you might need to set `idris-repl-prompt-style` to `'long` to avoid any confusion.

I've added the support here anyway: idris-lang/Idris-dev#1870
