### ISSUE TITLE
`do` not highlighted if inline with `then` or `else`

### ISSUE THREAD

**Issue by mindbound** [idris-hackers/idris-mode#296]
In this code, `do` is not being highlighted:
```idris
if x == "David"
then do incr; howManyDavids xs
else howManyDavids x
```
Putting the `do` block in a new line corrects the highlighting. I can replicate this with latest MELPA idris-mode.

**Comment by david-christiansen** [comment]
This is indeed an irritating bug, and I'd very much like to take care of it. I think the `font-lock` stuff needs a `t` somewhere to get it to double-highlight some things.

**Comment by david-christiansen** [comment]
This was fixed when the fancy highlighting regexps were removed in favor of compiler-supported highlighting. The new, simple, keyword-only regexps don't have these problems.
