### ISSUE TITLE
Everything but REPL working

### ISSUE THREAD

**Issue by andreasfrom** [idris-hackers/idris-mode#297]
Reporting this bug following [this comment](http://www.reddit.com/r/haskell/comments/2ty27b/dependently_typed_functional_programming_in_idris/co40m92).

I've installed Idris 0.9.16 in a cabal sandbox and put it in my PATH.
I've installed idris-mode using the `package-pinned-packages`-approach to get it from MELPA Stable and am running version 0.9.15.
Idris is in my `exec-path`.

After opening an Idris-file I can load it using `C-c C-l` and do all the interactive things like case-split, add missing clauses etc. The *idris-repl* buffer says "Welcome to the Idris REPL!" at the top and "Type checking ./Exercises1.idr" every time I do something interactive.

But if I switch to the *idris-repl* buffer and type for instance `2+2`, which produces `4 : Integer` on the command-line, then nothing happens. It goes to a newline without the prompt and stops accepting input.
If I do something interactive I get the prompt back until I try to use it again.

Below are the contents of various buffers, the last one is probably most interesting.

`*idris-repl*`

    Welcome to Idris REPL!
    Type checking ./Exercises1.idr
    λΠ> 2+2
    Type checking ./Exercises1.idr
    Type checking ./Exercises1.idr
    λΠ>

`*idris-events*` from typing `2+2` in the REPL, case-splitting, and then typing 2+3. It appears to return the right thing.

    11:59:13 -> ((:repl-completions "2")
     34)
    11:59:13 <- (:return
     (:ok
      (nil ""))
     34)
    11:59:14 -> ((:repl-completions "2+2")
     35)
    11:59:14 <- (:return
     (:ok
      (nil "2+"))
     35)
    11:59:14 -> ((:interpret "2+2")
     36)
    11:59:14 <- (:return
     (:ok "4 : Integer"
          ((0 1
              ((:decor :data)
               (:type "Integer")
               (:doc-overview "An arbitrary-precision integer")
               (:name "4")))
           (0 1
              ((:tt-term "AAAAAAAAAAAEAQAAAAAE")))
           (4 7
              ((:decor :type)
               (:type "Type")
               (:doc-overview "Arbitrary-precision integers")
               (:name "Integer")))
           (4 7
              ((:tt-term "AAAAAAAAAAAECg==")))))
     36)
    11:59:19 -> ((:load-file "Exercises1.idr")
     37)
    11:59:19 <- (:write-string "Type checking ./Exercises1.idr" 37)
    11:59:20 <- (:set-prompt "*Exercises1" 37)
    11:59:20 <- (:return
     (:ok
      ((:filename "Exercises1.idr")
       (:start 179 1)
       (:end 179 1)))
     37)
    11:59:20 -> ((:get-options)
     38)
    11:59:20 -> ((:case-split 178 "x")
     39)
    11:59:20 <- (:return
     (:ok
      ((:show-implicits :False)
       (:error-context :False)))
     38)
    11:59:20 <- (:return
     (:ok "not False = ?not_rhs_1\nnot True = ?not_rhs_2\n")
     39)
    11:59:22 -> ((:repl-completions "2")
     40)
    11:59:22 <- (:return
     (:ok
      (nil ""))
     40)
    11:59:22 -> ((:repl-completions "2+")
     41)
    11:59:22 <- (:return
     (:ok
      (("$>" "&&" "*" "+" "++" "-" "." "/" "/=" "::" "<" "<#>" "<$" "<$>" "<*>" "<+>" "<->" "<=" "<|>" "=" ...)
       "2+"))
     41)
    11:59:23 -> ((:repl-completions "2+2")
     42)
    11:59:23 <- (:return
     (:ok
      (nil "2+"))
     42)
    11:59:24 -> ((:repl-completions "2+3")
     43)
    11:59:24 <- (:return
     (:ok
      (nil "2+"))
     43)
    11:59:24 -> ((:interpret "2+3")
     44)
    11:59:24 <- (:return
     (:ok "5 : Integer"
          ((0 1
              ((:decor :data)
               (:type "Integer")
               (:doc-overview "An arbitrary-precision integer")
               (:name "5")))
           (0 1
              ((:tt-term "AAAAAAAAAAAEAQAAAAAF")))
           (4 7
              ((:decor :type)
               (:type "Type")
               (:doc-overview "Arbitrary-precision integers")
               (:name "Integer")))
           (4 7
              ((:tt-term "AAAAAAAAAAAECg==")))))
     44)

`*messages*` again from typing in the REPL, doing a case split and then typing again.
`Symbol's value as variable is void: &optional` is what I see in the mini-buffer after pressing enter in the REPL.

    Connected. Andreas, this could be the start of a beautiful proof.
    idris-repl-eval-string: Symbol's function definition is void: lexical-let
    error in process filter: idris-dispatch-event: Symbol's value as variable is void: &optional
    error in process filter: Symbol's value as variable is void: &optional
    Saving file /Users/andreasfrom/IdrisAtGalois2015/Lecture1/Exercises1.idr...
    Wrote /Users/andreasfrom/IdrisAtGalois2015/Lecture1/Exercises1.idr
    Auto-saving...done
    idris-repl-eval-string: Symbol's function definition is void: lexical-let
    error in process filter: idris-dispatch-event: Symbol's value as variable is void: &optional
    error in process filter: Symbol's value as variable is void: &optional

The rest of the `*idris-**` buffers are empty.

I have not looked into this myself, but hope the above information is useful.
Thanks for putting so much work into this project!

**Comment by david-christiansen** [comment]
I can see from the events log that Idris is evaluating things successfully and returning them to Emacs, but that Emacs is doing the wrong thing. It seems that it's not getting ahold of the `lexical-let` macro from `cl`, which for some reason is still necessary in that code... I should look into that, as normal Emacs lexical let bindings should be sufficient but weren't when I last looked.

Does it fix your problem if you do `M-: (require 'cl)` before opening an Idris file?

Out of curiosity, what does `M-x emacs-version` say?

**Comment by andreasfrom** [comment]
I'm terribly sorry about the timing, but I upgraded to Yosemite and switched to Nix so both my Emacs and Idris installs were lost. What I _can_ say is, that with idris-0.9.15.1 and `emacs-version` `GNU Emacs 24.4.1 (x86_64-apple-darwin14.1.0, Carbon Version 157 AppKit 1344.72) of 2015-01-30` it works flawlessly.

Should I close this?

**Comment by david-christiansen** [comment]
If we can't reproduce it then I suppose it should close for now. Hopefully it will turn up in search results for anyone else who might have the same issue.

I suspect that one of two things is happening:

1. It was Emacs 23 (with different scoping rules)

2. For some reason it's generating code at runtime that calls `eval` on a compile-time-only macro, and your new Emacs is putting that macro in the runtime scope by default.

In any case, thanks for a great bug report!
