### ISSUE TITLE
:unlet kills repl session

### ISSUE THREAD

**Issue by jasonhemann** [idris-hackers/idris-mode#299]
In the *idris-repl* buffer, 

λΠ> :let x : Nat ; x = 5 
defined
λΠ> :unlet x 

this then hangs. In idris-events, I see the following 

(:write-decorated
 ("Undefined x."
  ((10 1
       ((:name "x")
	(:implicit :False)))))
 20)

This same example works in a terminal session.

Idris> :let x : Nat ; x = 5
Idris> :unlet x
Undefined x.

**Comment by david-christiansen** [comment]
It seems that Idris never tells Emacs that it's done - it only sends "output side effect" messages, not "here's the result" messages.

**Comment by david-christiansen** [comment]
The new trace is:
```
13:17:15 -> ((:interpret ":let x : Nat ; x = 5")
 206)
13:17:15 <- (:return
 (:ok "defined")
 206)
13:17:19 -> ((:interpret ":unlet x")
 207)
13:17:19 <- (:return
 (:ok "Undefined x."
      ((10 1
           ((:name "x")
            (:implicit :False)))))
 207)
```

**Comment by david-christiansen** [comment]
Once this gets merged in Idris, I'll close the issue.
