### ISSUE TITLE
An instance in which C-c C-s improperly stubs out a function.

### ISSUE THREAD

**Issue by jasonhemann** [idris-hackers/idris-mode#300]
I have in a file only the following

module bar
Alias : Type
`--` 
foo : Nat -> String

Importantly, there's a single space after -- on the otherwise empty comment line, before the newline. When I hit C-c C-s with the mark on foo, it stubs it out with 
<code>
foo = ?foo_rhs
</code>
not 
<code>
foo k = ?foo_rhs 
</code>
as I was expecting. This is seemingly related to the following issue. If I delete the Alias line, as follows 

module bar
`--` 
foo : Nat -> String

when I type C-c C-s, it doesn't stub the function out at all. Instead I get in the minibuffer
<code>
Wrong type argument: number-or-marker-p, nil
</code>

**Comment by jasonhemann** [comment]
Ah. I've now tracked this to two independent issues:

1. In idris-mode, loading an empty module elicits the message "error in process filter: Wrong type argument: number-or-marker-p, nil" in the minibuffer. 
2. Idris-mode doesn't seem to like it when you end a line with the comment character then a space. If you do so, it'll instead comment out the following line. The module below, for instance, compiles.

````
module Foo
-- 
malformed stuff here
Alias : Type
Alias = Nat
````

Notice there's a space after <code>--</code> on the second line.

**Comment by david-christiansen** [comment]
This should be fixed in the latest Idris master version.
