### ISSUE TITLE
In most recent idris-mode, can't use automated theorem prover

### ISSUE THREAD

**Issue by jasonhemann** [idris-hackers/idris-mode#305]
I upgraded the idris-mode package to version: 20150219.246. Since, I haven't been able to use the proof script mode. The problem shows up even for a simple file

module Test
foo : Nat -> Bool
foo k = ?foo_rhs

I C-c C-l to load the file, and then [P] to enter proof script mode. When I try the intros tactic (when I M-n), I get the message:

error in process filter: Symbol's function definition is void: _result

and instead of green, the tactic is in orange. 

The full *messages* buffer is below:

ad-handle-definition: `tramp-read-passwd' got redefined
Helm completion enabled
For information about GNU Emacs and the GNU system, type C-h C-a.
Quit [2 times]
(No changes need to be saved)
Connected. Hacks and glory await!
/Users/jhemann/311/test-prover.ibc deleted
Preparing compiler note tree...
/Users/jhemann/311/test-prover.ibc deleted
Press q to close
idris-prover-script-forward: Symbol's function definition is void: lexical-let
error in process filter: Symbol's function definition is void: _result [2 times]

**Comment by jasonhemann** [comment]
Repl interaction was also broken. Uninstalling and reinstalling the most recent idris-mode seems to have solved it.

**Comment by david-christiansen** [comment]
Sounds like stale bytecode.
