### ISSUE TITLE
On a recent idris-mode on Mac OS X, asking for docs a variable named "Å" makes things go insane

### ISSUE THREAD

**Issue by david-christiansen** [idris-hackers/idris-mode#317]
It locks up in a solid loop with Idris complaining about `hGetCha: Invalid argument: Invalid byte sequencer` forever. The same bug does not occur on Debian.

It's probably an encoding or Unicode normalization discrepancy.

**Comment by hannesm** [comment]
could you capture with tcpdump what is actually transferred? I believe the coding system on both sides should finally be set to utf-8...

**Comment by david-christiansen** [comment]
I can't reproduce this myself - it was @sualitu's computer. Perhaps he can chime in?

**Comment by sualitu** [comment]
With the latest version of idris-mode I cannot reproduce this either.

**Comment by david-christiansen** [comment]
Thanks!
