### ISSUE TITLE
Metavariable Buffer - Expand and Prove buttons don't work

### ISSUE THREAD

**Issue by gonzaw** [idris-hackers/idris-mode#319]
I have certain proofs as metavariables, and when I open the buffer (C+c C+l) I want to try and prove them.
But pressing the expand [+] button doesn't do anything, nor does pressing the prove [P] button.
I'm attaching a screenshot

I'm using idris 0.9.17, Emacs 24.3.1 and the latest idris-mode.

![screenshot from 2015-03-29 02 30 36](https://cloud.githubusercontent.com/assets/6629501/6884214/aecfd9bc-d5bb-11e4-92ec-b489ec5457b9.png)

**Comment by david-christiansen** [comment]
`idris-mode` follows the somewhat old-school Emacs convention of using middle-click to press buttons. Does that work for you? It does for me, anyway.

**Comment by gonzaw** [comment]
Wow, I feel so stupid for not trying that. Thank you, it worked. I just started using Emacs so I wasn't aware of these conventions.
Thanks!

**Comment by david-christiansen** [comment]
You're not the first to be confused by this. It's a sign that we should
make the buttons left-clickable.
