### ISSUE TITLE
Who-calls and calls-who broken by info mode back button

### ISSUE THREAD

**Issue by david-christiansen** [idris-hackers/idris-mode#324]
The back button in the info mode breaks the display of trees. There are two problems:

 1. Tree buttons are overlays, which don't get properly saved/moved
 2. Trees have internal markers, which end up pointing into the wrong buffers

This can be fixed as follows:
 1. Use `insert-text-button` instead of `insert-button` to use text properties, which get saved in strings. Alternatively, serialize all overlays in an info buffer and save them along with the strings.
 2. When transferring information from the temporary buffer, save the markers and their positions into the info mode pages. Info mode insertion should then activate markers accordingly.

So probably the pages zipper should contain structs rather than strings, where the struct tracks the buffer contents as a string, the markers for that page, and (potentially) overlays for the page.

**Comment by david-christiansen** [comment]
I suppose there's a couple other ways to fix this:

* Allow pages in the info zipper to contain tree data as an alternative to strings, then show the tree. Or, more generally, a triple consisting of a pre-tree string, a post-tree string, and tree data.

* Stop using info buffers for trees, and show them in their own kind of output buffer.

**Comment by david-christiansen** [comment]
Given that there doesn't seem to be a way to capture all the markers in a buffer, these solutions might be better.

**Comment by hannesm** [comment]
I'd use a different kind of output buffer, and not put everything into info buffers.
