### ISSUE TITLE
error in process filter: make client process failed: connection refused

### ISSUE THREAD

**Issue by codygman** [idris-hackers/idris-mode#334]
I installed idris-mode from melpa with el-get and attempted to use C-c C-l on this file from the [http://docs.idris-lang.org/en/latest/tutorial/typesfuns.html](tutorial):

    module Prims
    
    x : Int
    x = 42
    
    foo : String
    foo = "Sausage machine"
    
    bar : Char
    bar = 'Z'
    
    quux : Bool
    quux = False

It gave this error:

    error in process filter: make client process failed: connection refused, :name, Idris Ideslave, :buffer, *idris-connection*, :host, 127.0.0.1, :service, 0, :nowait, nil
    Idris disconnected: exited abnormally with code 1
    idris-send: Buffer *idris-repl* has no process

**Comment by david-christiansen** [comment]
What versions of Emacs and Idris are you using? Is Idris on a path where
Emacs can see it, or is it hidden away in a Cabal sandbox? If the latter is
true, try customizing idris-interpreter-path.

**Comment by codygman** [comment]
Globally installed by cabal, Idris 0.9.14, and Emacs 24.3.1


    Welcome to the Emacs shell
    
    ~ $ idris
         ____    __     _                                          
        /  _/___/ /____(_)____                                     
        / // __  / ___/ / ___/     Version 0.9.14
      _/ // /_/ / /  / (__  )      http://www.idris-lang.org/      
     /___/\__,_/_/  /_/____/       Type :? for help               
    
    Idris is free software with ABSOLUTELY NO WARRANTY.            
    For details type :warranty.
    Idris> :q
    Bye bye
    ~ $ which idris
    /home/cody/.cabal/bin/idris
    ~ $ emacs --version
    GNU Emacs 24.3.1
    Copyright (C) 2013 Free Software Foundation, Inc.
    GNU Emacs comes with ABSOLUTELY NO WARRANTY.
    You may redistribute copies of Emacs
    under the terms of the GNU General Public License.
    For more information about these matters, see the file named COPYING.
    ~ $ which emacs
    /usr/bin/emacs

**Comment by hannesm** [comment]
is there an idris process running (check with `ps ax` in a terminal)? does it listen to a socket (`netstat -an | grep LISTEN`)? do you have a firewall setup?

**Comment by david-christiansen** [comment]
That's an ancient version of Idris. Would you please try with the latest release and see what happens?

**Comment by codygman** [comment]
Going to update Idris and retry. If I still get the error I'll check for
the Idris process/listening socket.

**Comment by david-christiansen** [comment]
This is still working fine for me with a recent Idris. Please re-open if it's still an issue once you've updated your Idris.

**Comment by marsam** [comment]
Hi, I'm also getting this error, with Emacs 24.5.1 and Idris from master. I've checked the process is listening, but seems a problem with the process filter. I'll send a pull request later ;)

**Comment by david-christiansen** [comment]
Thanks for the PR, @marsam!

**Comment by bbarker** [comment]
I seem to be having a similar issue; using the latest release from melp-stable for idris-mode, Idris 1.2.0, idris is running, but `netstat -an | grep idris` is empty. There should be no firewall set up, rather intentionally, as I'm running all this inside of a custom docker container. Is the port hardcoded by Idris, or what is the default port?

```
error in process filter: open-network-stream: make client process failed: Connection refused, :name, Idris IDE support, :buffer, *idris-connection*, :host, 127.0.0.1, :service, 0, :nowait, nil
```

**Comment by abailly** [comment]
@bbarker Are you running idris within a docker container? AFAICT it won't work because Idris hardcodes the IP address it binds to to `127.0.0.1`. I am also interested in having Idris run inside a container and started working on a patch to remove that limitation as it is rather easy (e.g. provide `--listen-to` argument with the actual default and sets it to `0.0.0.0` when running inside docker.

**Comment by bbarker** [comment]
Ah, yes, I see. I didn't realize localhost was an issue in a container. I
*try* to do all of my development in a docker container these days.

**Comment by abailly** [comment]
I also do the same. I proposed on the Idris ML to provide a Dockerfile for Idris as part of the standard source tree but this proposal was mildly received. If at least someone else is interested in packaging Idris in docker, I might give it a shot anyway.

**Comment by bbarker** [comment]
@abailly I've been running it in Nix, sort of; figuring out how to get nix working in docker was interesting, but luckily someone else had forged the way (and I ended up just using nixpkgs on top of and Ubuntu image). I imagine Nix would probably not be the most popular route, but with the Idris crowd maybe it would be. Unfortunately, I hit a recent snag when upgrading to 2.0.1, but haven't had time to look into it yet: https://github.com/NixOS/nix/issues/2121 Other than that, most things have been going well, and nixpkgs has the most recent version of Idris - it is also quite easy to get a haskell stack up and going there. I could pare down my dockerfile here if it is of interest: https://github.com/cornellcac/docker-nix-intellij.

Back to the issue at hand, I read about issues trying to use the loopback nic might be addressed by passing  `--cap-add net_raw --cap-add net_admin` to `docker run`, however, this did not seem to be workaround for me (same result as mentioned above).

**Comment by abailly** [comment]
The problem is not really about making an Idris container, that's trivial. But rather it is to make it possible to Idris listens on arbitrary interfaces rather than hardcoded localhost. Not that this is complex, it just requires some time and care.

**Comment by abailly** [comment]
Apologies if my answer sounded a bit arrogant, that was not intended. Anyhow, I definitely think one should not have to resort to byzantine network wizardry to run Idris inside a container and expose its port.
