### ISSUE TITLE
idris-set-idris-packages falls to recognise blank.

### ISSUE THREAD

**Issue by jfdm** [idris-hackers/idris-mode#355]
Trying to add packages for idris mode to recognise. The function `idris-set-idris-packages` fails to recognise the empty string to terminate the selection procedure.

Using

+ Idris Mode Head
+ Idris Head
+ GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7)

**Comment by david-christiansen** [comment]
This still works for me, and I've tested a few times. Are you using Helm for your completing read interface? If so, you need to enter the empty string with `C-RET` because `RET` selects the default candidate instead.

**Comment by jfdm** [comment]
@david-christiansen sadly, I do not use Helm. I am using ido still. This didn't used to be a problem, however your suggestion did not work for me although it was the solution. I had to invoke the return using `CRTL-SHIT-J` have return as a package and then delete the newline entry.

**Comment by david-christiansen** [comment]
This sounds like it might be an ido issue, or it might be a problem with how idris-mode is asking for a string.

**Comment by david-christiansen** [comment]
I just read the docs for `completing-read` again, and I'm pretty sure I'm using it right. This might be a bug in ido, or you might need to do something special to enter an empty selection.

**Comment by david-christiansen** [comment]
OK, so I went and played with it, and `ido-completing-read` doesn't make the empty string a possibility unless you supply it as an explicit option, unlike the built-in `completing-read` or the Helm version.

Supplying the empty list explicitly as an option makes `ido-completing-read` work fine, and it doesn't seem to get in the way of normal `completing-read` or Helm, so I'll add it.
