### ISSUE TITLE
Operator Fontification Improvements

### ISSUE THREAD

**Issue by jfdm** [idris-hackers/idris-mode#37]
In Version 20140106.1002 of Idris mode does not highlight case arrows `=>` properly. 

This is due to the complicated nature of building a regexp for operators, and including user defined operators.

Taking a leaf from Haskell Mode, a hacky-ish fix could be defining an explicit list of reserved operators---see https://github.com/haskell/haskell-mode/blob/master/haskell-font-lock.el#L272-L278. Then dealing with user defined operators in another way.

**Comment by david-christiansen** [comment]
Now, idris-mode leaves almost all highlighting up to Idris itself, and the syntax code has gotten much simpler. I'm going to close this, because the fancy highlighting that messed this up is now gone. Please re-open if I've misunderstood something.
