### ISSUE TITLE
[Spacemacs] `idris-load-file` should not popup the REPL (as in [Haskell])

### ISSUE THREAD

**Issue by xged** [idris-hackers/idris-mode#380]

**Comment by david-christiansen** [comment]
Do you mean that you think the REPL should exist, but not immediately become visible, or that it shouldn't be created? Why? Is this Spacemacs-specific, or a general request?

**Comment by xged** [comment]
Yes, I mean that the REPL should exist (`, s s`), but shouldn't popup when `, s b` is pressed (same functionality as in [Haskell]).

**Comment by david-christiansen** [comment]
I can add a setting for this - I like having the REPL show by default, but I can appreciate that not everybody does. Then, either your init.el or the Spacemacs layer can set this to "off".

**Comment by david-christiansen** [comment]
Also, writing `, s s` and `, s b` in an issue report doesn't help me understand what you mean. Please phrase these things in terms of the underlying command name or the default bindings - I can't memorize all the custom bindings from every config everywhere!

**Comment by xged** [comment]
@david-christiansen My bad (habit).

**Comment by hannesm** [comment]
but `load-file` behaves similar to `hol` and `dswank`/`dime`... I actually think that a REPL is very useful while programming idris (whereas not always needed for haskell)!? providing a configuration option (defaulting to `show repl on load-file`) sounds pretty ok to me (although the amount of tunables is already pretty large)

**Comment by xged** [comment]
@hannesm What is *tunables*?

**Comment by xged** [comment]
Are you ok, that after REPL pops, cursor is not on it? For me the cost of doing `idris-pop-to-repl` is the same as moving to another window.

**Comment by david-christiansen** [comment]
@hannesm this is something that I've hear other people complain about as well, so I think it's reasonable to put in the option. Really, I think the spec should be that interactive calls to `idris-repl`always show and pop to the REPL, while non-interactive calls follow a setting. I do share your concern about too many config options though - `idris-mode` is getting to be a bit complex to test.

@xged I really like having the cursor be in the REPL window, so I don't think we should change that.

**Comment by xged** [comment]
@david-christiansen 
> Are you ok, that after doing `idris-load-file`, cursor is **not** on the REPL window?
>> I really like having the cursor be in the REPL window, so I don't think we should change that

`idris-load-file` pops up the REPL window, but **does not** move the cursor to the REPL window in Spacemacs.

**Comment by david-christiansen** [comment]
I blame jetlag for having written wrong there :)
