### ISSUE TITLE
[Spacemacs] Would be cool if `up` and `down` would scroll threw history

### ISSUE THREAD

**Issue by xged** [idris-hackers/idris-mode#381]
`up` (`down`) should do `idris-repl-backward-history` (`idris-repl-forward-history`) by default as in *terminal*, not `C-up` and `C-down`.

**Comment by david-christiansen** [comment]
This is not the ordinary Emacs convention for REPLs. Is it a Spacemacs-specific customization that's done in other modes? If so, can you link me to one or two of them so I can see how they arrange for that?

**Comment by xged** [comment]
You are correct, it is not the ordinary Emacs convention, but it has to be! :-). `j``k` does what `down``up` does anyway.

**Comment by david-christiansen** [comment]
What do you mean by "`j k` does what `down up` does anyway"? Do you mean that this should be closed? Or are you documenting a different Spacemacs convention?

**Comment by xged** [comment]
I meant, that remapping `down``up` has no cost, because at this moment `down``up` do the same as `j``k` (moving down and up).

**Comment by hannesm** [comment]
I do not understand at all this issue (well, and I'm ignorant towards spacemacs). `down up` in idris-mode behaves like `down up` in `M-x shell`. Why should its behaviour be different?

**Comment by xged** [comment]
>

**Comment by xged** [comment]
> Is it a Spacemacs-specific customization that's done in other modes?

It is done in all of the Spacemacs shells, including `M-x shell`.

> down up in idris-mode behaves like down up in M-x shell

Not the case for me.

**Comment by david-christiansen** [comment]
@xged Would you please find out where this customization is done? My guess is that you need to make a change to the idris-mode layer in Spacemacs to remap the keys.

**Comment by xged** [comment]
@david-christiansen [spacemacs/pull](https://github.com/syl20bnr/spacemacs/pull/943)

    (eval-after-load "shell"
      '(progn
        (evil-define-key 'insert comint-mode-map [up] 'comint-previous-input)
        (evil-define-key 'insert comint-mode-map [down] 'comint-next-input)))

**Comment by david-christiansen** [comment]
Looks to me like you should add something similar to the `idris-mode` Spacemacs layer.

**Comment by xged** [comment]
@david-christiansen Works just in insert-mode (good enough).
(You) Add this to Spacemacs (idk how :-).

    (eval-after-load "idris-repl"
      '(progn
         (define-key idris-repl-mode-map [up] 'idris-repl-backward-history)
         (define-key idris-repl-mode-map [down] 'idris-repl-forward-history)))

P.S.: `idris-repl-delete-curent-input` needs a binding to `C-c C-c`

**Comment by david-christiansen** [comment]
I believe you get code into Spacemacs with a pull request to https://github.com/syl20bnr/spacemacs/tree/master/contrib/!lang/extra-langs .

**Comment by david-christiansen** [comment]
Closing because this really is something for the Spacemacs layer rather than for `idris-mode`.
