### ISSUE TITLE
Upon building I get this: Error: reference to free variable `idris-hole-show-on-load'

### ISSUE THREAD

**Issue by kevinsullivan** [idris-hackers/idris-mode#385]
I just did a git pull and then make. I get the following error. Note that my "emacs24" is symlinked to an emacs24 that I just built from sources. When I tried to build with the ubuntu24 that I had, I got some other errors, as well. Are these problems real problems? Or should I avoid using this version of this mode until things clear up? Thanks! --Kevin

$ make
emacs24 --batch --no-site-file -q -eval '(add-to-list (quote load-path) "/home/cs1/System/Idris-emacs-mode-dev/idris-mode/")' -eval '(require (quote package))' -eval '(add-to-list (quote package-archives) (quote ("melpa" . "http://melpa.org/packages/")) t)' -eval '(package-initialize)' -eval '(progn (require (quote bytecomp)) (setq byte-compile-warnings t) (setq byte-compile-error-on-warn t))' -f batch-byte-compile idris-commands.el

In toplevel form:
idris-commands.el:93:9:Error: reference to free variable `idris-hole-show-on-load'
make: **\* [idris-commands.elc] Error 1

**Comment by david-christiansen** [comment]
I can't reproduce this on my machine. What does `emacs --version` say? Idris mode only works on 24.3 and higher.
