### ISSUE TITLE
Colors: What is the difference between `idris-identifier-face` and `idris-semantic-function-face` ?

### ISSUE THREAD

**Issue by xged** [idris-hackers/idris-mode#387]
E.g. I found `Prelude.Functor.map` being both of these *faces* in different files.

**Comment by david-christiansen** [comment]
`idris-identifier-face` is applied by `font-lock` - that is, it's determined using regexps, and it may even be obsolete now that we have semantic highlighting from the compiler. `idris-semantic-function-face` is applied by the compiler after type checking, when it can see that the thing in question is indeed a user-defined operator (most often a function).
