### ISSUE TITLE
git clone followed by make fails

### ISSUE THREAD

**Issue by kevinsullivan** [idris-hackers/idris-mode#400]
Build appears to be broken in master. Git clone followed immediately by make yields this error:

idris-mode.el:192:1:Error: the function `idris-make-cases-from-hole' is not known to be defined.

**Comment by david-christiansen** [comment]
It works for me, and Travis runs for all pull requests to ensure that the build doesn't break.  `idris-make-cases-from-hole` is defined in `idris-commands.el`, which `idris-mode.el` `require`s.

Would you please post the entire build output?

**Comment by david-christiansen** [comment]
Also, what does `emacs --version` say?

**Comment by kevinsullivan** [comment]
With apologies I was unable to reproduce the reported error on a second copy of my VM.

**Comment by david-christiansen** [comment]
No need to apologize :-) I'm happy it works!
