### ISSUE TITLE
iPKG Mode unable to find Idris executable.

### ISSUE THREAD

**Issue by jfdm** [idris-hackers/idris-mode#403]
Trying to setup a work flow for my idris projects that is purely within Emacs. When building a project, *idris-mode* complains abotu not being able to find the `idris` command. The error is:

```
-*- mode: compilation; default-directory: "~/projects/idris/packages/eggs/" -*-
Compilation started at Sat Sep 26 09:43:47

idris --build eggs.ipkg
zsh:1: command not found: idris

Compilation exited abnormally with code 127 at Sat Sep 26 09:43:47
```

The path to the idris executable has been set via `idris-mode` and see not options for setting a path for idris within the iPKG options.

**Comment by jfdm** [comment]
Actually, I think idris mode is not connecting to idris. I am getting a resource consumption blow up. Will do some numpty checks, and report.

**Comment by jfdm** [comment]
So removal of a `.dir-local.el` helped with the connection issues (twas using old name of the variable for declaring packages.). However, when I point idris mode to the iPKG file for my executable, idris cannot be found.

**Comment by david-christiansen** [comment]
Here's the bug: https://github.com/idris-hackers/idris-mode/commit/9925390c00c5146da50994e8dce9105767176f7f#L231

Thanks for finding it! I'll fix it in the next couple of days.

**Comment by jfdm** [comment]
Cheers.
