### ISSUE TITLE
function highlighting not working

### ISSUE THREAD

**Issue by anthoq88** [idris-hackers/idris-mode#407]
Hello, I don't know if I'm doing something wrong here. But syntax highlighting for functions doesn't seem to be working for me.

I've installed it using melpa which is installed under the folder `idris-mode-20150930/`

![screen shot 2015-10-02 at 7 10 48 am](https://cloud.githubusercontent.com/assets/1674432/10233957/e98a35e6-68d4-11e5-98c5-cf42a5dd00f5.png)

**Comment by david-christiansen** [comment]
Idris doesn't color identifiers until type checking has occurred. This is because type information is necessary to determine the meaning of each identifier and select the right color. Have you done a `C-c C-l` yet?

**Comment by anthoq88** [comment]
That worked - however, I also had to make sure that my idris version was up to date.
Thanks!

**Comment by david-christiansen** [comment]
In general, make sure to keep your idris-mode synchronized with your Idris. I try not to break compatibility, but it's sometimes necessary for progress.
