### ISSUE TITLE
Goals with function type are shown in a strange way

### ISSUE THREAD

**Issue by kosmikus** [idris-hackers/idris-mode#417]
The following sample program
```
module Fun

test : List Char
test = map ?f [1, 2, 3]
```
produces the following output in my `idris-holes` buffer:
```
Holes

This buffer displays the unsolved holes from the currently-loaded code. Press
the [E] buttons to solve the holes interactively in the prover.

- + Fun.f [E]
 `--          a : Type
          class : Functor List
      __pi_arg6 : Integer
     --------------------------
      Fun.f : Char
```
I would much prefer if the type of `f` was shown to be `Integer -> Char`.

Screenshot:
![Screenshot](http://kosmikus.org/~andres/idris-emacs.png)

**Comment by david-christiansen** [comment]
In IRC, you mentioned that this behavior is different from Atom, which surprised me quite a lot, given that they both use the same compiler interfaces. Can you show me what Atom is doing with a quick screenshot as well?

**Comment by kosmikus** [comment]
@david-christiansen You are right. It isn't really different in Atom. It's just that Atom does not show the holes by default, and I usually just ask for he type for the hole. This indeed works fine in Emacs as well. C-c C-t shows
```
  a : Type
--------------------------------------
Fun.f : Integer -> Char
```
more or less as expected.

Using the `Language Idris: Holes` command in Atom exhibits the same problem as Emacs. So I guess it is actually an Idris bug ...

**Comment by david-christiansen** [comment]
OK, thanks, I'll migrate the issue over.  Appreciate it!

**Comment by david-christiansen** [comment]
See https://github.com/idris-lang/Idris-dev/issues/2940 to track this issue.

**Comment by kosmikus** [comment]
Thanks a lot for migrating the issue.

**Comment by david-christiansen** [comment]
No prob! Thanks for pointing it out :-)
