### ISSUE TITLE
Highlight the new export keyword

### ISSUE THREAD

**Issue by colin-adams** [idris-hackers/idris-mode#418]
With 0.10.1 a new export modifier "export" is available. This should be highlighted the same as private and public.

**Comment by jeffersoncarpenter** [comment]
Version 0.10 adds the `interface` and `implementation` keywords, which should be highlighted as well.

Just added them to the lists - is this all that would need to be done?

**Comment by david-christiansen** [comment]
Thanks for fixing this, @jeffersoncarpenter!

**Comment by colin-adams** [comment]
Is this update supposed to be automatically available on melpa (because I
can't see it there)? Excuse me, but I'm quite ignorant of how the update
process is supposed to work.

**Comment by david-christiansen** [comment]
Yes, it should come on MELPA within a day or so. If you're using MELPA-stable, it will wait until I tag a release, which will probably happen in the not-so-distant future.
