### ISSUE TITLE
display in browse isn't taking the implicitness into account

### ISSUE THREAD

**Issue by jasonhemann** [idris-hackers/idris-mode#422]
When I look up weakenN from the Fin library (via apropos) I get an expected type. Yet when I browse the namespace I get a different, though seemingly also reasonable type. I thought that perhaps the definition had been changed to the latter, but it seems the former is still correct. @david-christiansen , you mentioned that the display in browse isn't taking the implicitness into account. I attach an image below.

![bug](https://cloud.githubusercontent.com/assets/1329370/14398474/7c8714c8-fdb2-11e5-832a-9660313bb614.png)

**Comment by david-christiansen** [comment]
Confirmed. For comparison, the `:browse` at the REPL does what it should.

**Comment by david-christiansen** [comment]
Though this is actually a bug in Idris itself, rather than the Emacs mode.

**Comment by david-christiansen** [comment]
This is working for me now, so I think someone fixed it. How about you?

**Comment by david-christiansen** [comment]
Please re-open if it's still an issue for you.
