### ISSUE TITLE
C-c C-s vs C-c C-a

### ISSUE THREAD

**Issue by reuleaux** [idris-hackers/idris-mode#425]
Following Edwin's book, I learned that at least for Atom the key board is defined as:

- Ctrl-Alt-S  - search (easy to remember: "s" for search),
- and Ctrl-Alt-A for Add definition ("a" for add)

Now I learned that in Emacs' Idris mode by default it's the other way around:

-  C-c C-a		idris-proof-search
-  C-c C-s		idris-add-clause

I wonder what's the rationale for this? maybe 
"a" for automatic ? but "s" for idris-add-clause ?

then I tried to redefine those keys (exchange them), with something like

  (defun my-idr-mode-hook ()
    (define-key idris-mode-map               (kbd "C-c C-s") 'idris-proof-search)
    (define-key idris-mode-map               (kbd "C-c C-a") 'idris-add-clause)
  )

  (add-hook 'idris-mode-hook #'my-idr-mode-hook)

but without success so far, likewise with use-package/bind

  (use-package idris

      :init
      (progn
	(setq idris-interpreter-path "~/idr/latest/.cabal-sandbox/bin/idris")

	)

      :bind (

	     ("C-c C-s" . idris-proof-search)
	     ("C-c C-a" . idris-add-clause)
       )	   
  )

maybe I am on the wrong key map ? I saw that there's tons of them:
idris-mode-map, 
idris-info-mode-map, 
idris-ipkg-mode-map, 
idris-log-mode-map,
idris-repl-mode-map, 
idris-hole-list-mode-map,
etc

Any advice ?

Thanks in advance.

**Comment by david-christiansen** [comment]
The keybindings in `idris-mode` are chose for compatibility with the other modes that inspired it. The first priority is compatibility with `agda-mode`, and after that, compatibility with `slime`. 

`C-c C-a` is from Agda, and it's short for "auto".   Agda doesn't have an equivalent of `idris-add-clause`, but the mnemonic is `s` for "start definition".

For custom bindings, I'd just rebind them directly in the `:config` section of `use-package`.  These two keys are only relevant in `idris-mode-map`, so you can try something like:
```
(define-key idris-mode-map (kbd "C-c C-s") 'idris-proof-search)
(define-key idris-mode-map (kbd "C-c C-a") 'idris-add-clause)
```

Also, this isn't a bug in `idris-mode`, so I'm going to close it. I think that the Idris mailing list or IRC channel would be a better place to ask these kinds of questions.

**Comment by david-christiansen** [comment]
Also, I'm not sure why the hook isn't working. Have you tried to put a call to `message` in your hook procedure to see that it gets called?

**Comment by reuleaux** [comment]
OK, I see: s for "start definition", and a for "auto" (like in Agda etc.),
and I managed to rebind them now: I had to put the

  (defun my-idr-mode-hook ()
	(define-key idris-mode-map               (kbd "C-c C-s") 'idris-proof-search)
	(define-key idris-mode-map               (kbd "C-c C-a") 'idris-add-clause)
	)
      
  (add-hook 'idris-mode-hook #'my-idr-mode-hook)

code in the :init section of my use-package definition (not sure, why it wasn't working
when I had it in the :config section), but fine with me.

So sorry for the noise, and thanks for the explanations.

**Comment by david-christiansen** [comment]
You're welcome!
