### ISSUE TITLE
Holes have wrong type

### ISSUE THREAD

**Issue by houli** [idris-hackers/idris-mode#427]
Holes presented in the Emacs mode do not have the correct type.

Steps to reproduce:
Using Idris 0.12.2 and the latest Idris mode 20160302
Create a new file with the following code

``` idris
totalLen : List String -> Nat
totalLen xs = foldr ?sumLength 0 xs
```

Load the file with Idris mode.
Outcome: 
<img width="303" alt="screen shot 2016-08-21 at 19 19 23" src="https://cloud.githubusercontent.com/assets/143868/17842119/789123ae-67d4-11e6-98f3-12a8992a43af.png">

Expected: 
<img width="313" alt="screen shot 2016-08-21 at 19 19 32" src="https://cloud.githubusercontent.com/assets/143868/17842124/7ec0bcda-67d4-11e6-9552-8b98ba1b75ad.png">

The second screenshot is from the Idris command line in my terminal which correctly displays the type of `sumLength` and doesn't include the `__class` and `__pi_arg` variables.

**Comment by david-christiansen** [comment]
This is how the non-editor-connected Idris REPL used to work, so my guess is that some code got updated in one place instead of two.

Thanks for the report! If you want to get to it before I can, then take a look at how the implementations of `:t` at the REPL and the corresponding IDE command differ. It should be in `REPL.hs` in the compiler.

**Comment by houli** [comment]
Just wondering if there's been any updates on this? The Idris codebase is a bit beyond me figuring out the changes that need to happen here

**Comment by david-christiansen** [comment]
No, I haven't gotten to this yet. Life is busy!

**Comment by houli** [comment]
No problems

**Comment by david-christiansen** [comment]
Once https://github.com/idris-lang/Idris-dev/pull/3597 is merged, this will be fixed. Thanks for your patience!
