### ISSUE TITLE
idris-proof-search deletes the hole when proof search returns no result

### ISSUE THREAD

**Issue by enolan** [idris-hackers/idris-mode#428]
In this snippet:

``` idris
swap : (a, b) -> (b, a)
swap (a, b) = (?swap_rhs_2, ?swap_rhs_3)
```

Placing the point over the 's' in `swap_rhs_2` and running `idris-proof-search` gives:

``` idris
swap : (a, b) -> (b, a)
swap (a, b) = (, ?swap_rhs_3)
```

Which doesn't parse. At the repl, `:proofsearch` gives no result:

```
*/home/enolan/junk/stackoverflow> :proofsearch 2 swap_rhs_2
Holes: Main.swap_rhs_4, Main.swap_rhs_3
*/home/enolan/junk/stackoverflow> 
```

(I was writing a StackOverflow answer) This in on Idris 0.12.2-git:8d42e43 and idris-mode-20160302.645.

**Comment by david-christiansen** [comment]
It certainly shouldn't do this! I suppose that the proof search in the compiler is sending a blank string rather than an error when it can't find an answer, but that'll need looking into.

Thanks!
