### ISSUE TITLE
LICENSE file 

### ISSUE THREAD

**Issue by siddharthist** [idris-hackers/idris-mode#432]
I can't seem to find the license for this code. From http://choosealicense.com/no-license [1]:

> You’ll have to check with your own legal counsel regarding your particular project, but generally speaking, the absence of a license means that default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work.

Did you intend for this code to be open source? If so, can you upload a license, or point me to it?

Thanks!

(note: it looks like the individual files have license comments, but overall guidance for the project would be great!)

[1]: See also: the Berne Convention, the international law: http://zvon.org/law/r/bern.html#intro

**Comment by vyp** [comment]
COPYING?

**Comment by siddharthist** [comment]
@vyp Oh, duh. Thanks!

**Comment by vyp** [comment]
No worries!

**Comment by hannesm** [comment]
this is (unfortunately) GPL3 code since we inherit(ed?) code from haskell-mode (I guess the indentation stuff)... I'm happy to relicense the parts I wrote under whatever license you like (usually I do BSD2)... OTOH it is an emacs mode and shouldn't affect any software produced by using this mode AFAIU

**Comment by david-christiansen** [comment]
There's also lots of code inherited from DIME, which so far as I can see is GPL 1 or later. In any case, I don't agree that the GPL is unfortunate here. Having everything in Emacs be under the same terms makes things easier, not harder.
