### ISSUE TITLE
`idris-stay-in-current-window-on-compiler-error` doesn't work in spacemacs

### ISSUE THREAD

**Issue by ExpHP** [idris-hackers/idris-mode#440]
Detailed bug report here https://github.com/syl20bnr/spacemacs/issues/8354 .

tl;dr: `idris-stay-in-current-window-on-compiler-error` doesn't work in spacemacs, and I'm not sure which of the two projects is to blame.

(speaking as a complete noob at emacs: at a cursory glance it seems to me that "display-buffer" is simply not sufficient to prevent focus-stealing; but I also don't know if there isn't some crazy hacks going on deep down inside spacemacs to cause this!)

**Comment by david-christiansen** [comment]
Thanks for the report! Because it does work fine in vanilla Emacs, I'm inclined to think that it's a side-effect of something done in Spacemacs. But if you find a way to change the code so that it works fine in both vanilla Emacs and Spacemacs, I'll happily accept a pull request.

**Comment by ExpHP** [comment]
Upon further review, [I think the ball is in their court](https://github.com/syl20bnr/spacemacs/issues/8354#issuecomment-279620030) due to popwin configuration with `:noselect nil` properties.

If others run into trouble with this, the following snippet of user configuration can be used to override it:

```elisp
(defun dotspacemacs/user-config ()
  ; ...
  (with-eval-after-load 'idris-mode
    (setq idris-stay-in-current-window-on-compiler-error t)
    (dolist (x '("*idris-notes*" "*idris-holes*" "*idris-info*"))
      (plist-put (cdr (assoc x popwin:special-display-config)) :noselect t))
  )
)
```

**Comment by jfdm** [comment]
Maybe it is time to start an FAQ for emacs-mode with this snippet in it.

**Comment by david-christiansen** [comment]
I don't know that a separate FAQ is necessary, but it certainly makes sense in the README.

**Comment by david-christiansen** [comment]
OK, it's there. Thanks for investigating, @ExpHP!
