### ISSUE TITLE
Case splitting is position-dependant

### ISSUE THREAD

**Issue by ether42** [idris-hackers/idris-mode#441]
Hi there,

I stumbled upon a curious issue while trying out some exercises of "Type-Driven Development with Idris", this doesn't feel quite right to me but I may be wrong so please, feel free to correct me/close this issue if I am (I did a quick search for similar issues/pull requests but didn't find closely related).

I'll start with a simple `example.idr` file:
```idris
example : Bool -> a -> a
```

I use `C-c C-s` with the point on `example` to get an hole:
```idris
example : Bool -> a -> a
example x y = ?example_rhs
```

Imagine I want to case split with `C-c C-c` the `?example_rhs` hole for the sake of showing my issue.
Depending on where I'll place the point, I'll get different results:
 - `?`: `Can’t make cases from ?`
 - the first `e` of `example` or on `rhs`: `example_rhs is not a pattern variable (synchronous Idris evaluation failed)`
 - anywhere on `xample_`: I'll get the following case split which I was expecting:
```idris
example : Bool -> a -> a
example x y = case _ of
                   case_val => ?example_rhs
```

It may be easier to understand with a record of a session: https://asciinema.org/a/0c8uyo0g43r47xztmu41gab8o

I'm on the latest commit: b5e057b.

**Comment by david-christiansen** [comment]
Thanks for a careful and thorough report! We recently replaced the code that finds the variable name under the cursor, so this is probably fallout from that.

I'm totally swamped with work right now, unfortunately, so I can't really fix this myself for a little while. If you'd like to take a run at it, I can point you to likely parts of the codebase, though.

**Comment by ether42** [comment]
Okay, so after some experimentation, I may have found some relevant things in `idris-commands.el` (I'm no expert in Elisp, please beer with me :)):
 - function `idris-case-dwim`'s condition doesn't call `idris-make-cases-from-hole` as I expected:
   - `looking-at-p` and `looking-back` functions have mismatching regexps, I think the pattern should be something like `\?[a-zA-Z0-9_]+` so it could match `?example_rhs` (I emphasize on `0-9` as some holes may contains numbers)
   - `looking-back` doesn't seems to be the right thing to use if I correctly understood the documentation (https://www.gnu.org/software/emacs/manual/html_node/elisp/Regexp-Search.html#index-looking_002dback), it starts matching before the point and stop right at it
   - I'm unsure about Emacs regexp here: is it necessary to use `\\?` instead of `\?` 
   - shouldn't we use a function to retrieve the whole word under the point (a bit like `idris-thing-at-point` and try to match `\?[a-zA-Z0-9_]+` on the result? This would guarantee that we don't match only on the half of the word as `looking-at-p` and `looking-back` seems to do here
 - function `idris-thing-at-point`:
   - I'm unsure if it should be modified to return `?example_rhs` when the point is on `?`, it actually only returns `?` so it explains the error message `Can’t make cases from ?`
