### ISSUE TITLE
idris-make-lemma doesn't handle correctly functions with explicit totality options.

### ISSUE THREAD

**Issue by sirikid** [idris-hackers/idris-mode#442]
#### First case, one or more newlines between the totality option and the function declaration
What I did
```idris
total/partial
foo : Unit
foo = ?foo_rhs -- C-c C-e
```
What I expected
```idris
foo_rhs : ()

total/partial
foo : Unit
foo = foo_rhs
```
What I got
```idris
total/partial
foo_rhs : ()

foo : Unit
foo = foo_rhs
```
#### Second case, one or more spaces between the totality option and the function declaration
What I did
```idris
total/partial foo : Unit
foo = ?foo_rhs -- C-c C-e
```
What I expected
```idris
foo_rhs : ()

total/partial foo : Unit
foo = foo_rhs
```
What I got
```idris
total/partial foo : Unit
foo = foo_rhs
```
and message about failed search by regex

#### System info
GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.7) of 2017-02-07
idris-mode 20161102.707

**Comment by abailly** [comment]
@sirikid Is this fixed as the commit's comment suggest? If so, can you provide a PR?

**Comment by sirikid** [comment]
@abailly no, if it was so, I would have already made a PR.
