### ISSUE TITLE
idris-repl annoying insert-point jump

### ISSUE THREAD

**Issue by dstechenko** [idris-hackers/idris-mode#443]
When I load a file for the first time I get this annoying insert-point jump. 
It also happens sometimes when I keep reloading/rechecking the file, like maybe once in 5-15 reloads.

I tried looking into this, but spent some time and could not push a decent PR. 
Only some hacks to prevent this from happening. 
The problem appears to be connected to the process of update-prompt handling.

macOS Sierra 10.12.4
GNU Emacs 25.2.1 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21) of 2017-02-05

Starts like this:
<img width="1440" alt="fst" src="https://cloud.githubusercontent.com/assets/5430434/25077217/b7bfba68-22f5-11e7-9c4f-8a5a81fb2162.png">

Ends like this:
<img width="1440" alt="snd" src="https://cloud.githubusercontent.com/assets/5430434/25077218/b7c8fa9c-22f5-11e7-9f7b-3d96e44edd73.png">

Hope this helps.

**Comment by abailly** [comment]
@dstechenko is this still bugging you?
