### ISSUE TITLE
Emacs hangs if idris-events gets too big

### ISSUE THREAD

**Issue by mrkgnao** [idris-hackers/idris-mode#444]
Is there a way to decrease the verbosity of the logging? I often have my `idris-events` buffer grow to 5-6 MB. Clearing it works wonders.

**Comment by hannesm** [comment]
unfortunately there's no way to decrease verbosity -- atm all communication between idris and idris-mode is logged.   it should rather be a ringbuffer, i.e. truncated after N messages (or M bytes).

**Comment by david-christiansen** [comment]
This is a good idea. It might also be a good idea to disable the logging by default, now that idris-mode is relatively stable.
