### ISSUE TITLE
idris-simple-indent-backtab infinite loop?

### ISSUE THREAD

**Issue by camelpunch** [idris-hackers/idris-mode#449]
When I try to `(idris-simple-indent-backtab)` when my cursor is anywhere on the line containing `"Some B"` of the following file, Emacs hangs until I `c-g`.

```idris
record Foo where
  constructor MkFoo
  a : String
  b : String

mylist : List Foo
mylist =
  [ MkFoo "Some A"
                          "Some B"
  ]
```

**Comment by david-christiansen** [comment]
Thanks for a good issue report with a nice test case!

**Comment by camelpunch** [comment]
I can confirm this fixes the problem. Thanks @werbitt !
