### ISSUE TITLE
Warnings show as errors in Flycheck mode.

### ISSUE THREAD

**Issue by gatoWololo** [idris-hackers/idris-mode#451]
Currently, warnings are marked the same red color as errors in the buffer. I'm currently using Idris 1.0.

By looking at your `flycheck-define-checker`, the issue seems to be this line:
```
((warning line-start (file-name) ":" line ":" column ":Warning - "
```

Running idriss on the command line:

```
>  idris --check --nocolor --warnpartial temp.idr 
temp.idr:5:1:
Warning - Main.f is possibly not total due to: Prelude.Interfaces.Int implementation of Prelude.Interfaces.Integral
```

So adding a newline character to the the warning string fixed this for me.

**Comment by jfdm** [comment]
Thanks for the feedback, if you want to submit a PR to fix this then please do.

**Comment by david-christiansen** [comment]
Thanks very much!

I don't use the Flycheck integration, but I do welcome a fix. Thanks again!
