### ISSUE TITLE
idris-set-idris-load-packages doesn't seem to work

### ISSUE THREAD

**Issue by shmish111** [idris-hackers/idris-mode#452]
Excuse my emacs ignorance, I'm new. I am unable to enter a blank line as it gives options as to the packages available, pressing return will simply add the first package in the list. If I just keep pressing return until there are no more options in the list it doesn't ever seem to give me the prompt "Use the packages %s for this session?". I only managed to get things working by manually evaluating the idris-load-packages var.

**Comment by jfdm** [comment]
From what i remember you can use `ctrl+f` to insert a newline. The inclusion of a blank line is linked to a hook iirc...not really sure on the details. @david-christiansen will know more.

**Comment by david-christiansen** [comment]
My guess is that you're using Helm, in which case `C-RET` is the technique for entering a blank string.

**Comment by shmish111** [comment]
On my mac, `alt-enter` worked
