### ISSUE TITLE
idris mode doesn't find other source files

### ISSUE THREAD

**Issue by shmish111** [idris-hackers/idris-mode#459]
If I have a project based in a folder called src, I need to tell idris by passing the `-i` parameter, e.g. `idris -i src` however there seems to be no way I can do this in idris mode. This means I cannot use interactive environment for a file that imports another module in my project. Is there some way to pass this parameter to the idris process in idris mode?

**Comment by jfdm** [comment]
hi @shmish111 you will be interested in Idris' support for packages. 

http://idris.readthedocs.io/en/latest/tutorial/packages.html

Idris Mode is package aware.

**Comment by david-christiansen** [comment]
The way to do this is indeed to use a package. If this doesn't work for you, please re-open the issue.
