### ISSUE TITLE
Cannot start inferior-idris-process

### ISSUE THREAD

**Issue by themattchan** [idris-hackers/idris-mode#460]
I'm trying to`C-c C-l` a file in emacs, but it keeps on failing with the following error:

```idris-send: Buffer Exotic.idr has no process
Idris disconnected: exited abnormally with code 1
Warning from Idris: The following packages were specified but cannot be found:
- idris

Idris disconnected: exited abnormally with code 1
Warning from Idris: The following packages were specified but cannot be found:
- idris
```

I installed idris through `brew install idris`, and have set the path in emacs: `(setq idris-interpreter-path "/usr/local/bin/idris")`. I'm on `idris v 1.1.1` and the latest version of `idris-mode` on MELPA.

Any help would be appreciated. Thanks!

**Comment by david-christiansen** [comment]
It sounds to me like Idris is getting the argument "-p idris". Have you specified anything on `idris-load-packages`?

**Comment by themattchan** [comment]
Nope, when I `C-x C-e` on `idris-load-packages` I get `nil`

**Comment by themattchan** [comment]
Weird, I only get this error when I'm inside the project for [1]... could this be some weird interaction with `ipkg`?

[1]:https://github.com/vmchale/recursion_schemes

**Comment by abailly** [comment]
@themattchan is still an issue?

**Comment by gergoerdi** [comment]
I'm seeing a similar problem, are these related?

```
Warning from Idris: The following packages were specified but cannot be found:

Warning from Idris: - effects
- js
- contrib

Idris disconnected: exited abnormally with code 1

```

Of course, just loading the same file from the CLI with `--package js --package effects --package contrib` works.

**Comment by jsoo1** [comment]
@gergoerdi It looks like the original requester mentioned that `idris-load-packages` was `nil`.  Would you mind creating a separate issue?

@themattchan I think the original issue is that idris-mode doesn't recognize all idris identifiers in package names in `.ipkg` packages. I opened https://github.com/idris-hackers/idris-mode/pull/488 to address that issue.
