### ISSUE TITLE
Annoying Popups (and Solution)

### ISSUE THREAD

**Issue by freckletonj** [idris-hackers/idris-mode#461]
I've seen the pitch for Pop Win, but found my use case was simple enough to not need it.

I have a bit of a unique use case perhaps, in that I use XMonad, and emacs' `frames-only-mode` which makes emacs play nice with a tiling manager.

As such, `idris-mode` aggressively pops up buffers and moves me into them, and when I hit `q` to close it, the frame remains, and within minutes of playing with idris, I'll have half a dozen extra windows open.

The solution is to tell `frames-only-mode` to that when certain buffers are killed, so should their frames.

Solution:

```
(add-to-list 'frames-only-mode-kill-frame-when-buffer-killed-buffer-list "*idris-repl*")
(add-to-list 'frames-only-mode-kill-frame-when-buffer-killed-buffer-list "*idris-events*")
(add-to-list 'frames-only-mode-kill-frame-when-buffer-killed-buffer-list "*idris-connection*")
(add-to-list 'frames-only-mode-kill-frame-when-buffer-killed-buffer-list "*idris-process*")
(add-to-list 'frames-only-mode-kill-frame-when-buffer-killed-buffer-list "*idris-notes*")
(add-to-list 'frames-only-mode-kill-frame-when-buffer-killed-buffer-list "*idris-info*")
```

(PS, thanks for idris and idris-mode, quite enlightening)

**Comment by david-christiansen** [comment]
Thanks for this! Would you be willing to phrase these instructions as an update to the README and send a pull request?

**Comment by freckletonj** [comment]
done! https://github.com/idris-hackers/idris-mode/pull/462

**Comment by jfdm** [comment]
Looks like this issue is complete.
