### ISSUE TITLE
Misaligned Literate Idris highlightling in `idris-mode`

### ISSUE THREAD

**Issue by fabianhjr** [idris-hackers/idris-mode#480]
```
> data Day = Monday
>          | Tuesday
>          | Wednesday
>          | Thursday
>          | Friday
>          | Saturday
>          | Sunday
>
> next_weekday : Day -> Day
> next_weekday d = case d of
>                      Monday    => Tuesday
>                      Tuesday   => Wednesday
>                      Wednesday => Thursday
>                      Thursday  => Friday
>                      Friday    => Saturday
>                      Saturday  => Sunday
>                      Sunday    => Monday
```

# Steps to Reproduce

1. Save code as Literate.lidr
2. `idris-load-file` in Emacs with `idris-mode`

# Expected Behavior

Correct highlighting

# Observed Behavior

Highlighting shifts 2 places to the left. (Corresponding to the `> ` in the editor)

![screenshot from 2018-06-14 23-39-20](https://user-images.githubusercontent.com/303897/41450392-f4967a28-702c-11e8-8a94-84492ace79cb.png)

# Software Info

`idris --version`: 1.3.0-git:PRE
`emacs --version`: GNU Emacs 26.1

Related: idris-lang/idris-dev#1736

Crosspost from idris-lang/idris-dev#4478

**Comment by ska80** [comment]
I don't have this issue:

![screen shot 2018-06-15 at 11 58 10](https://user-images.githubusercontent.com/92121/41450694-8de91378-7093-11e8-9c0b-e5f856d3cded.png)

`idris --version`: 1.3.0-git:88a9f38f
`emacs --version`: GNU Emacs 26.1

`idris-mode`: latest, installed from MELPA

**Comment by fabianhjr** [comment]
Thanks @ska80, I will double check my configs to see if there is something messing with my buffer.

**Comment by andrewmcveigh** [comment]
I do have this issue, did you solve it?

**Comment by andrewmcveigh** [comment]
Seems to be down to this function:

```elisp
(defun idris-highlight-column (idris-col)
  "Compute the Emacs position offset of the Idris column IDRIS-COL, for highlighting.

In particular, this takes bird tracks into account in literate Idris."
  (+ idris-col (if (idris-lidr-p) 1 -1)))
```

Changing it to this "fixes" the offset for me.

```elisp
(defun idris-highlight-column (idris-col)
  "Compute the Emacs position offset of the Idris column IDRIS-COL, for highlighting.

In particular, this takes bird tracks into account in literate Idris."
  (+ idris-col (if (idris-lidr-p) -1 -1)))
```
Maybe something in the back end changed for `.lidr`?

**Comment by lrworth** [comment]
@fabianhjr @andrewmcveigh I too have this issue. Was there some resolution found before the ticket was closed?

I'm using Spacemacs with the idris layer. I can fix it the same way @andrewmcveigh suggested.

**Comment by fabianhjr** [comment]
I don't remember how I fixed it but it was an issue on my end.

**Comment by jjl** [comment]
I just upgraded idris-mode from melpa and see the same problem. evaluating the code by @andrewmcveigh also fixes it.
