### ISSUE TITLE
link http://itu.dk/people/drc/pubs/dtp2014-idris-mode.pdf broken

### ISSUE THREAD

**Issue by MarisaKirisame** [idris-hackers/idris-mode#484]
The link is in Readme.md

**Comment by BerberBerthold** [comment]
Is this dead link the only full documentation?  Because I noticed the same with the dead link, and I can't find the full documentation anywhere else.

**Comment by jsoo1** [comment]
I think it might just be. Luckily the source is included in the repo (see documentation.tex). I’m not sure where we’d host a pdf and how we’d keep it up to date.

**Comment by david-christiansen** [comment]
The PDF is here: http://davidchristiansen.dk/pubs/dtp2014-idris-mode.pdf

I think updating the link should be sufficient. But I suppose that
http://docs.idris-lang.org/en/latest/reference/ide-protocol.html is
probably more interesting for most people.
