### ISSUE TITLE
Remove support for emacs 24?

### ISSUE THREAD

**Issue by jsoo1** [idris-hackers/idris-mode#492]
Should idris-mode still support emacs 24? The current release is version 26.1. How many people are still using 24? idris-mode also uses some functions that have since changed. It seems that maybe supporting more than one version back could be a maintenance burden considering how few people are working on it.

**Comment by david-christiansen** [comment]
Good question! I usually like to support whatever is in Debian Stable, and
stretch still has 24. So I'd want to wait for buster to become stable first.

I know we have at least one user who sticks to Debian stable.

**Comment by jsoo1** [comment]
Ok sounds good. It stays.
