### ISSUE TITLE
Strange syntax highlighting

### ISSUE THREAD

**Issue by mhwombat** [idris-hackers/idris-mode#498]
I am using idris-mode  0.9.19. I got it from Melpa Stable, but I think it's the same version that's on GitHub. I am seeing a strange effect with syntax highlighting. When I first load in Idris source file, only certain keywords are in colour.

![screen1](https://user-images.githubusercontent.com/1899200/56396159-7eb39d80-6235-11e9-9e78-e6ac402f7af1.png)

Then, If I load the file into the Idris REPL, identifiers are in colour, but the last character of each identifier is not in colour.

![screen2](https://user-images.githubusercontent.com/1899200/56396216-bc182b00-6235-11e9-9421-823568bcafc7.png)

Here is a minimal emacs configuration which reproduces this behaviour.

```
;; No startup screen
(setq inhibit-startup-screen t)

;; open with single window
(add-hook 'emacs-startup-hook 'delete-other-windows)

;; Repos
(require 'package) ;; This is built-in
(add-to-list 'package-archives
             '("gnu" . "http://elpa.gnu.org/packages/") t)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/") t)
(add-to-list 'package-archives
             '("melpa-stable" . "http://stable.melpa.org/packages/") t)
(package-initialize)
;; (package-refresh-contents)
```

**Comment by jsoo1** [comment]
Thanks for the report! Two things:

 - We get close to all syntax highlighting from the compiler. That’s why you only get colors after loading a file

- The syntax highlighting certainly looks off by one.

What version of idris do you have?

**Comment by jsoo1** [comment]
Hmm. Actually now that I look at it, I think our melpa-stable is quite out of date. Could you try plain melpa and let me know what happens?

**Comment by mhwombat** [comment]
Upgrading to the plain melpa version fixed it. Thank you!
