### ISSUE TITLE
Implement Idris 2 proof-search-next IDE Protocol command

### ISSUE THREAD

**Issue by scotek** [idris-hackers/idris-mode#510]
Idris 2 provides a new protocol command (`proof-search-next`) to iterate through multiple attempts to solve a hole.  It would be nice to support this in `idris-mode`, especially since Edwin mentions it a lot now in talks.

I don't think it is documented yet but appears in the code (https://github.com/idris-lang/Idris2/blob/14604dcf2d344d225fc1a36e77228e8e99a9d0ec/src/Idris/IDEMode/Commands.idr#L96) and is in at least the Idris vim mode.

**Comment by scotek** [comment]
I've added my PR that implements this.  There is a caveat given in it around having to limit the basic `proof-search` command for Idris 1 to work around issue #509 though.

**Comment by jfdm** [comment]
Cool thanks! I am not sure why #509 is happening, and do not have the time to look into that, but *I* do not see any reason my #511 should  not be added.

**Comment by scotek** [comment]
Ok.  Do you want me to remove the now-unused variable code in `proof-search-next` so it passes the tests?  If we eventually figure out why the optional args don't work then we can just revert that single commit to get them back.

**Comment by jfdm** [comment]
I think it would be reasonable to do that, and also post an email to the mailing list. Someone might be able to help who knows better.

**Comment by jfdm** [comment]
Fixed in #511
