### ISSUE TITLE
Case splitting results in non-unique hole name

### ISSUE THREAD

**Issue by scotek** [idris-hackers/idris-mode#512]
Continuing from idris-lang/Idris2#566 , case-splitting can omit the last character resulting in non-unique hole names.

Removing the `1-` call in the handling on `idris-case-split` in gets the full output to appear for me (https://github.com/idris-hackers/idris-mode/blob/b77eadd8ac2048d5c882b4464bd9673e45dd6a59/idris-commands.el#L582).  The root cause seems to go back to #466 .

The problem appears to affect `idris-make-cases-from-hole` as well, with the same fix. I'll look at a couple of other possible places then do a PR.

**Comment by jfdm** [comment]
@scotek Thanks for the contribution, I think what we are seeing are differences slowly appearing in the ide-protocol. So we either ensure that the ide-protocol implementations are kept the same or we need to diverge... TBH your observation in #513 is rather prudent:

> We may need to look at adding a setting to indicate Idris 1 vs 2 and tweak some of these functions but that needs a separate discussion.

IIRC the ide-protocol does allow one to get the Idris version from the compiler, maybe we need to check/extend the ide-protocol with protocol versioning to allow a mode to be backwards and forward compatible. I am happy to mentor this, and it is something we should raise on the mailing list for action.

**Comment by jfdm** [comment]
fixed in #513 and #519
