### ISSUE TITLE
[idris2-mode] "Unused lexical variable 'name'"

### ISSUE THREAD

**Issue by gergoerdi** [idris-hackers/idris-mode#543]
Precompiling `idris2-mode` with the included `Makefile` fails with the following error message:

```
emacs --batch --no-site-file -q -eval '(add-to-list (quote load-path) "/home/cactus/prog/idris/idris2/bugs/emacs-mode/.emacs.d/elisp/idris2-mode/")' -eval '(require (quote package))' -eval '(add-to-list (quote package-archives) (quote ("melpa" . "http://melpa.org/packages/")) t)' -eval '(package-initialize)' -eval '(progn (require (quote bytecomp)) (setq byte-compile-warnings t) (setq byte-compile-error-on-warn t))' -f batch-byte-compile idris2-commands.el

In toplevel form:
idris2-commands.el:365:1:Error: Unused lexical variable ‘name’
```

This can be worked around by setting `byte-compile-error-on-warn` to `nil`, but of course it would be better if someone actually looked at `idris2-commands.el` and see if `idris2-jump-to-location` has some error in it.

**Comment by jfdm** [comment]
Sorry for the late reply, I have not hat time to do as much maintenance on Idris-mode as I would like. I cannot promise that I will get to this, but PRs are more than welcome. Thanks.

**Comment by gallais** [comment]
Should this bug report be moved to https://github.com/idris-community/idris2-mode?

**Comment by jfdm** [comment]
i didn't realise it was Idris2! Then of course it should.

**Comment by jfdm** [comment]
There is a transfer option! @gallais feel free to do that. You should have privileges.

**Comment by gallais** [comment]
I don't think it's possible to transfer an issue across organisations.

**Comment by gallais** [comment]
I'm assuming this has been fixed by https://github.com/idris-community/idris2-mode/pull/9
