### ISSUE TITLE
idris-mode should have the possibility of passing package arguments to idris

### ISSUE THREAD

**Issue by hannesm** [idris-hackers/idris-mode#6]
(this was in the old repo, which I removed)

several solutions come to mind:
- an option `-pall` for idris to load all packages
- heuristic to find packages
- specify used packages inside of source file (first line, with some special notation)

**Comment by cameron-martin** [comment]
I added

```
-- Local Variables:
-- idris-packages: ("effects")
-- End:
```

to the bottom of my file, but I still get an error `Can't find import Effects` when loading the program.

Is this still a valid way of doing things?

**Comment by bixuanzju** [comment]
@cameron-martin 
> The variable idris-packages has been renamed to idris-load-packages. If you have this as a file variable, please rename it.
